<?php

/**
 * @file
 * WxT Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter for blocks.
 */
function THEMENAME_theme_suggestions_block_alter(&$suggestions, $variables) {

  // Load theme suggestions for blocks from parent theme.
  foreach ($suggestions as &$suggestion) {
    $suggestion = str_replace('THEMENAME_', 'wxt_bootstrap_', $suggestion);
  }
}
